before_install:
- openssl aes-256-cbc -K $encrypted_4fffec2486cd_key -iv $encrypted_4fffec2486cd_iv
  -in deploy-key.enc -out deploy-key -d
language: ruby
rvm:
  - 2.4.3
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  ssh_known_hosts: kjaer.io
before_install:
  - bash _scripts/install.sh
script:
  - bash _scripts/build.sh
  - bash _scripts/test.sh
after_success:
  - bash _scripts/deploy.sh